# VERSION 1.1
all_nuts = (
        'calories', 'protein', 'carbs', 'fiber', 'fat', 'cholesterol', 'calcium', 'iron', 'magnesium', 'potassium',
        'sodium', 'zinc', 'vitamin a', 'thiamine', 'vitamin e', 'riboflavin', 'niacin', 'vitamin b6', 'folate',
        'vitamin c', 'vitamin b12', 'selenium', 'sugar', 'vitamin d')

daily_doses = {
    'fiber': (38, 'grams'),
    'carbs': (500, 'grams'),
    'fat': (80, 'grams'),
    'protein': (270, 'grams'),
    'vitamin a': (100, 'ug', 3000),
    'vitamin d': (5, 'ug', 50),
    'vitamin e': (15, 'mg', 1000),
    'vitamin k': (120, 'ug'),
    'vitamin c': (100, 'ug', 1000),
    'thiamine': (1.2, 'mg'),
    'riboflavin': (1.2, 'mg'),
    'niacin': (16, 'mg', 35),
    'folate': (400, 'ug', 1000),
    'vitamin b6': (1.3, 'mg', 100),
    'vitamin b12': (2.4, 'ug'),
    'biotin': (30, 'mg'),
    'sodium': (1500, 'mg', 2300),
    'calcium': (1000, 'mg', 2500),
    'phosphorus': (700, 'mg', 4000),
    'magnesium': (400, 'mg', 350),
    'potassium': (4700, 'mg'),
    'iron': (8, 'mg'),
    'zinc': (11, 'mg', 40),
    'selenium': (0, 'ug', 400),
    'calories': 3500,
    'sugar': (0, 'g', 40),
    'cholesterol': (0, 'mg', 300)
}


foods = {
    'whole wheat': {
        'quantity': 1,
        'measure': 'slice',
        'calories': 128,
        'protein': 4,
        'carbs': 24,
        'fiber': 3,
        'fat': 2,
        'cholesterol': 0,
        'calcium': 15,
        'iron': 1.43,
        'magnesium': 37,
        'potassium': 144,
        'sodium': 159,
        'zinc': .69,
        'vitamin a': 0,
        'thiamine': 0.14,
        'vitamin e': 0.35,
        'riboflavin': 0.10,
        'niacin': 1.83,
        'vitamin b6': 0.09,
        'folate': 30,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 18,
        'sugar': 1.6,
        'vitamin d': 0
    },
    'turkey bacon': {
        'quantity': 1,
        'measure': 'item',
        'calories': 35,
        'protein': 4,
        'carbs': 0,
        'fiber': 0,
        'fat': 2,
        'cholesterol': 10,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 180,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'whey shake': {
        'quantity': 1,
        'measure': 'scoop',
        'calories': 270,
        'protein': 28,
        'carbs': 18,
        'fiber': 3,
        'fat': 10.5,
        'cholesterol': 90,
        'sugar': 13,
        'vitamin d': 8,
        'calcium': 500,
        'iron': 0,
        'magnesium': 100,
        'potassium': 550,
        'sodium': 215,
        'zinc': 5.2,
        'vitamin a': 75,
        'thiamine': 1.5,
        'vitamin e': 0,
        'riboflavin': 1.7,
        'niacin': 0,
        'vitamin b6': 2,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0
    },
    'olive oil': {
        'quantity': 1,
        'measure': 'teaspoon',
        'calories': 119,
        'protein': 0,
        'carbs': 0,
        'fiber': 0,
        'fat': 14,
        'calcium': 0,
        'iron': 0.09,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 0,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 1.94,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'cholesterol': 55,
        'sugar': 2,
        'vitamin d': 5,
    },
    'canola oil': {
        'quantity': 1,
        'measure': 'teaspoon',
        'calories': 120,
        'protein': 0,
        'carbs': 0,
        'fiber': 0,
        'fat': 14,
        'cholesterol': 20,
        'calcium': 0,
        'iron': 2.16,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 0,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 2.33,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'french dressing': {
        'quantity': 2,
        'measure': 'tablespoons',
        'calories': 143,
        'protein': 0,
        'carbs': 5,
        'fiber': 0,
        'fat': 14,
        'cholesterol': 0,
        'calcium': 7,
        'iron': 0.25,
        'magnesium': 2,
        'potassium': 21,
        'sodium': 261,
        'zinc': 0.09,
        'vitamin a': 7,
        'thiamine': 0.01,
        'vitamin e': 1.56,
        'riboflavin': 0.02,
        'niacin': 0.06,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'blueberry muffin': {
        'quantity': 1,
        'measure': 'item',
        'calories': 160,
        'protein': 3,
        'carbs': 21,
        'fiber': 1,
        'fat': 6,
        'cholesterol': 20,
        'calcium': 50,
        'iron': 1.15,
        'magnesium': 7,
        'potassium': 56,
        'sodium': 288,
        'zinc': 0.39,
        'vitamin a': 20,
        'thiamine': 0.14,
        'vitamin e': 0.76,
        'riboflavin': 0.15,
        'niacin': 1.14,
        'vitamin b6': 0.03,
        'folate': 29,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 9,
        'sugar': 2,
        'vitamin d': 5
    },
    'cinnamon and raisin bagel': {
        'quantity': 1,
        'measure': 'item',
        'calories': 195,
        'protein': 7,
        'carbs': 39,
        'fiber': 2,
        'fat': 1,
        'cholesterol': 0,
        'calcium': 13,
        'iron': 2.70,
        'magnesium': 20,
        'potassium': 105,
        'sodium': 229,
        'zinc': 0.80,
        'vitamin a': 15,
        'thiamine': 0.27,
        'vitamin e': 0.22,
        'riboflavin': 0.20,
        'niacin': 2.19,
        'vitamin b6': 0.04,
        'folate': 79,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 22,
        'sugar': 2,
        'vitamin d': 5
    },
    'jasmine rice': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 340,
        'protein': 8,
        'carbs': 78,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 20,
        'calcium': 0,
        'iron': 2.16,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 780,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'grapefruit': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 48,
        'protein': 1,
        'carbs': 12,
        'fiber': 2,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 25,
        'iron': 0.09,
        'magnesium': 10,
        'potassium': 155,
        'sodium': 0,
        'zinc': 0.08,
        'vitamin a': 30,
        'thiamine': 0.05,
        'vitamin e': 0.15,
        'riboflavin': 0.03,
        'niacin': 0.23,
        'vitamin b6': 0.06,
        'folate': 15,
        'vitamin c': 36,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'strawberries': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 23,
        'protein': 0,
        'carbs': 6,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 12,
        'iron': 0.3,
        'magnesium': 9,
        'potassium': 110,
        'sodium': 1,
        'zinc': 0.10,
        'vitamin a': 1,
        'thiamine': 0.02,
        'vitamin e': 0.21,
        'riboflavin': 0.02,
        'niacin': 0.28,
        'vitamin b6': 0.03,
        'folate': 17,
        'vitamin c': 42,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'apples': {
        'quantity': 1,
        'measure': 'item',
        'calories': 72,
        'protein': 0,
        'carbs': 19,
        'fiber': 3,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 3,
        'iron': 0.07,
        'magnesium': 3,
        'potassium': 59,
        'sodium': 1,
        'zinc': 0.02,
        'vitamin a': 2,
        'thiamine': 0.01,
        'vitamin e': 0,
        'riboflavin': 0.01,
        'niacin': 0.05,
        'vitamin b6': 0.02,
        'folate': 2,
        'vitamin c': 3,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'honeydew melon': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 32,
        'protein': 0,
        'carbs': 8,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 5,
        'iron': 0.15,
        'magnesium': 9,
        'potassium': 203,
        'sodium': 16,
        'zinc': 0.08,
        'vitamin a': 3,
        'thiamin': 0.03,
        'vitamin e': 0.02,
        'riboflavin': 0.01,
        'niacin': 0.37,
        'vitamin b6': 0.08,
        'folate': 17,
        'vitamin c': 16,
        'vitamin b12': 0,
        'selenium': 1,
        'sugar': 2,
        'vitamin d': 5
    },
    'banana': {
        'quantity': 1,
        'measure': 'item',
        'calories': 105,
        'protein': 1,
        'carbs': 27,
        'fiber': 3.1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 6,
        'iron': 0.31,
        'magnesium': 32,
        'potassium': 422,
        'sodium': 1,
        'zinc': 0.18,
        'vitamin a': 4,
        'thiamine': 0.04,
        'vitamin e': 0.12,
        'riboflavin': 0.09,
        'niacin': 0.78,
        'vitamin b6': 0.43,
        'folate': 24,
        'vitamin c': 10,
        'vitamin b12': 0,
        'selenium': 1,
        'sugar': 2,
        'vitamin d': 5
    },
    'cherries': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 46,
        'protein': 1,
        'carbs': 12,
        'fiber': 2,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 9,
        'iron': 0.26,
        'magnesium': 8,
        'potassium': 161,
        'sodium': 0,
        'zinc': 0.05,
        'vitamin a': 2,
        'thiamine': 0.02,
        'vitamin e': 0.05,
        'riboflavin': 0.02,
        'niacin': 0.11,
        'vitamin b6': 0.04,
        'folate': 3,
        'vitamin c': 5,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'orange juice': {
        'quantity': 1,
        'measure': 'cup',
        'calories': 112,
        'protein': 2,
        'carbs': 26,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 350,
        'iron': 0.50,
        'magnesium': 48,
        'potassium': 450,
        'sodium': 0,
        'zinc': 0.12,
        'vitamin a': 0,
        'thiamine': 0.22,
        'vitamin e': 0.10,
        'riboflavin': 0.08,
        'niacin': 1,
        'vitamin b6': 0.10,
        'folate': 76,
        'vitamin c': 90,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 22,
        'vitamin d': 2.5
    },
    'peaches': {
        'quantity': 1,
        'measure': 'item',
        'calories': 38,
        'protein': 1,
        'carbs': 9,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 6,
        'iron': 0.25,
        'magnesium': 9,
        'potassium': 186,
        'sodium': 0,
        'zinc': 0.17,
        'vitamin a': 16,
        'thiamine': 0.02,
        'vitamin e': 0.51,
        'riboflavin': 0.02,
        'niacin': 0.79,
        'vitamin b6': 0.02,
        'folate': 4,
        'vitamin c': 6,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'romaine lettuce': {
        'quantity': 1,
        'measure': 'cup',
        'calories': 10,
        'protein': 1,
        'carbs': 2,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 19,
        'iron': 0.55,
        'magnesium': 8,
        'potassium': 139,
        'sodium': 5,
        'zinc': 0.13,
        'vitamin a': 163,
        'thiamin': 0.04,
        'vitamin e': 0.07,
        'riboflavin': 0.04,
        'niacin': 0.18,
        'vitamin b6': 0.04,
        'folate': 77,
        'vitamin c': 14,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'mashed potatoes': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 119,
        'protein': 2,
        'carbs': 18,
        'fiber': 2,
        'fat': 4,
        'cholesterol': 1,
        'calcium': 21,
        'iron': 0.27,
        'magnesium': 20,
        'potassium': 342,
        'sodium': 350,
        'zinc': 0.32,
        'vitamin a': 43,
        'thiamine': 0.10,
        'vitamin e': 0.44,
        'riboflavin': 0.05,
        'niacin': 1.23,
        'vitamin b6': 0.26,
        'folate': 9,
        'vitamin c': 11,
        'vitamin b12': 0,
        'selenium': 1,
        'sugar': 2,
        'vitamin d': 5
    },
    'sweet potatoe': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 126,
        'protein': 2,
        'carbs': 29,
        'fiber': 4,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 45,
        'iron': 1.2,
        'magnesium': 30,
        'potassium': 382,
        'sodium': 45,
        'zinc': 0.33,
        'vitamin a': 1310,
        'thiamin': 0.09,
        'vitamin e': 1.56,
        'riboflavin': 0.08,
        'niacin': 0.89,
        'vitamin b6': 0.27,
        'folate': 10,
        'vitamin c': 21,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'asparagus': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 20,
        'protein': 2,
        'carbs': 4,
        'fiber': 2,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 21,
        'iron': 0.81,
        'magnesium': 13,
        'potassium': 202,
        'sodium': 13,
        'zinc': 0.54,
        'vitamin a': 49,
        'thiamin': 0.14,
        'vitamin e': 1.35,
        'riboflavin': 0.12,
        'niacin': 0.97,
        'vitamin b6': 0.07,
        'folate': 134,
        'vitamin c': 7,
        'vitamin b12': 0,
        'selenium': 5,
        'sugar': 2,
        'vitamin d': 5
    },
    'broccoli': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 27,
        'protein': 2,
        'carbs': 6,
        'fiber': 3,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 31,
        'iron': 0.52,
        'magnesium': 16,
        'potassium': 229,
        'sodium': 32,
        'zinc': 0.35,
        'vitamin a': 76,
        'thiamine': 0.05,
        'vitamin e': 1.13,
        'riboflavin': 0.10,
        'niacin': 0.43,
        'vitamin b6': 0.16,
        'folate': 84,
        'vitamin c': 51,
        'vitamin b12': 0,
        'selenium': 1,
        'sugar': 2,
        'vitamin d': 5
    },
    'carrots': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 25,
        'protein': 1,
        'carbs': 8,
        'fiber': 2,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 20,
        'iron': 0.4,
        'magnesium': 0,
        'potassium': 270,
        'sodium': 65,
        'zinc': 0.0,
        'vitamin a': 300,
        'thiamine': 0.00,
        'vitamin e': 0.0,
        'riboflavin': 0.0,
        'niacin': 0.0,
        'vitamin b6': 0.0,
        'folate': 0,
        'vitamin c': 7,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 5,
        'vitamin d': 0
    },
    'cauliflower': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 14,
        'protein': 1,
        'carbs': 3,
        'fiber': 2,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 10,
        'iron': 0.20,
        'magnesium': 6,
        'potassium': 88,
        'sodium': 9,
        'zinc': 0.11,
        'vitamin a': 1,
        'thiamine': 0.03,
        'vitamin e': 0.04,
        'riboflavin': 0.03,
        'niacin': 0.25,
        'vitamin b6': 0.11,
        'folate': 27,
        'vitamin c': 27,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'celery': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 8,
        'protein': 1,
        'carbs': 3,
        'fiber': 2,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 24,
        'iron': 0.12,
        'magnesium': 7,
        'potassium': 157,
        'sodium': 48,
        'zinc': 0.08,
        'vitamin a': 13,
        'thiamine': 0.01,
        'vitamin e': 0.16,
        'riboflavin': 0.03,
        'niacin': 0.19,
        'vitamin b6': 0.04,
        'folate': 22,
        'vitamin c': 2,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'corn': {
        'quantity': 1,
        'measure': 'item',
        'calories': 107,
        'protein': 3,
        'carbs': 25,
        'fiber': 3,
        'fat': 1,
        'cholesterol': 0,
        'calcium': 2,
        'iron': 0.60,
        'magnesium': 32,
        'potassium': 248,
        'sodium': 242,
        'zinc': 0.47,
        'vitamin a': 22,
        'thiamine': 0.21,
        'vitamin e': 0.09,
        'riboflavin': 0.07,
        'niacin': 1.6,
        'vitamin b6': 0.05,
        'folate': 0,
        'vitamin c': 6,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'lentils': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 115,
        'protein': 9,
        'carbs': 20,
        'fiber': 8,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 19,
        'iron': 3.30,
        'magnesium': 36,
        'potassium': 365,
        'sodium': 2,
        'zinc': 1.26,
        'vitamin a': 0,
        'thiamine': 0.17,
        'vitamin e': 0.11,
        'riboflavin': 0.07,
        'niacin': 1.05,
        'vitamin b6': 0.18,
        'folate': 179,
        'vitamin c': 1,
        'vitamin b12': 0,
        'selenium': 3,
        'sugar': 2,
        'vitamin d': 5
    },
    'peas': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 64,
        'protein': 4,
        'carbs': 11,
        'fiber': 4,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 19,
        'iron': 1.22,
        'magnesium': 18,
        'potassium': 88,
        'sodium': 58,
        'zinc': 0.54,
        'vitamin a': 84,
        'thiamine': 0.23,
        'vitamin e': 0.02,
        'riboflavin': 0.08,
        'niacin': 1.18,
        'vitamin b6': 0.09,
        'folate': 47,
        'vitamin c': 8,
        'vitamin b12': 0,
        'selenium': 1,
        'sugar': 2,
        'vitamin d': 5
    },
    'fried tofu': {
        'quantity': 3,
        'measure': 'ounce',
        'calories': 230,
        'protein': 15,
        'carbs': 9,
        'fiber': 3,
        'fat': 17,
        'cholesterol': 0,
        'calcium': 316,
        'iron': 4.14,
        'magnesium': 51,
        'potassium': 124,
        'sodium': 14,
        'zinc': 1.69,
        'vitamin a': 1,
        'thiamine': 0.14,
        'vitamin e': 0.03,
        'riboflavin': 0.04,
        'niacin': 0.09,
        'vitamin b6': 0.08,
        'folate': 23,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 24,
        'sugar': 2,
        'vitamin d': 5
    },
    'spinach': {
        'quantity': 1,
        'measure': 'cup',
        'calories': 7,
        'protein': 1,
        'carbs': 1,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 30,
        'iron': 0.81,
        'magnesium': 24,
        'potassium': 167,
        'sodium': 24,
        'zinc': 0.16,
        'vitamin a': 141,
        'thiamine': 0.02,
        'vitamin e': 0.61,
        'riboflavin': 0.06,
        'niacin': 0.22,
        'vitamin b6': 0.06,
        'folate': 58,
        'vitamin c': 8,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'sweet potato': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 126,
        'protein': 2,
        'carbs': 29,
        'fiber': 4,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 45,
        'iron': 1.20,
        'magnesium': 30,
        'potassium': 382,
        'sodium': 45,
        'zinc': 0.33,
        'vitamin a': 1310,
        'thiamine': 0.09,
        'vitamin e': 1.56,
        'riboflavin': 0.08,
        'niacin': 0.89,
        'vitamin b6': 0.27,
        'folate': 10,
        'vitamin c': 21,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'tomatoes': {
        'quantity': 1,
        'measure': 'item',
        'calories': 22,
        'protein': 1,
        'carbs': 5,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 12,
        'iron': 0.33,
        'magnesium': 14,
        'potassium': 292,
        'sodium': 6,
        'zinc': 0.20,
        'vitamin a': 76,
        'thiamine': 0.04,
        'vitamin e': 0.66,
        'riboflavin': 0.02,
        'niacin': 0.73,
        'vitamin b6': 0.09,
        'folate': 18,
        'vitamin c': 16,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'pinto beans': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 25,
        'protein': 2,
        'carbs': 5,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 17,
        'iron': 0.75,
        'magnesium': 20,
        'potassium': 111,
        'sodium': 58,
        'zinc': 0.19,
        'vitamin a': 76,
        'thiamine': 0.08,
        'vitamin e': 0,
        'riboflavin': 0.07,
        'niacin': 0.82,
        'vitamin b6': 0.09,
        'folate': 146,
        'vitamin c': 7,
        'vitamin b12': 0,
        'selenium': 1,
        'sugar': 2,
        'vitamin d': 5
    },
    'sirloin steak': {
        'quantity': 1,
        'measure': 'item',
        'calories': 280,
        'protein': 43,
        'carbs': 0,
        'fiber': 0,
        'fat': 12,
        'cholesterol': 125,
        'calcium': 17,
        'iron': 3.7,
        'magnesium': 19,
        'potassium': 286,
        'sodium': 48,
        'zinc': 5.7,
        'vitamin a': 11.5,
        'thiamine': 0.1,
        'vitamin e': 0.8,
        'riboflavin': 0.5,
        'niacin': 0.82,
        'vitamin b6': 0.5,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 1.4,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'chocolate croissant': {
        'quantity': 1,
        'measure': 'item',
        'calories': 272,
        'protein': 5.5,
        'carbs': 31,
        'fiber': 1.7,
        'fat': 14,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 313,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 7.5,
        'vitamin d': 0
    },
    'whole milk': {
        'quantity': 1,
        'measure': 'cup',
        'calories': 160,
        'protein': 8,
        'carbs': 12,
        'fiber': 0,
        'fat': 9,
        'cholesterol': 35,
        'calcium': 300,
        'iron': 0,
        'magnesium': 0,
        'potassium': 370,
        'sodium': 125,
        'zinc': 0,
        'vitamin a': 75,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 11,
        'vitamin d': 3
    },
    'egg white': {
        'quantity': 1,
        'measure': 'item',
        'calories': 17,
        'protein': 4,
        'carbs': 1,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 2,
        'iron': 0.03,
        'magnesium': 4,
        'potassium': 54,
        'sodium': 55,
        'zinc': 0.01,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0.24,
        'niacin': 0.04,
        'vitamin b6': 0.07,
        'folate': 1,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 7,
        'sugar': .6,
        'vitamin d': 0
    },
    'oatmeal': {
        'quantity': 1,
        'measure': 'bowl',
        'calories': 230,
        'protein': 10,
        'carbs': 40,
        'fiber': 4,
        'fat': 5,
        'cholesterol': 10,
        'calcium': 50,
        'iron': 1.8,
        'magnesium': 0,
        'potassium': 210,
        'sodium': 180,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0.0,
        'vitamin b6': 0.0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'chicken soup': {
        'quantity': 1,
        'measure': 'bowl',
        'calories': 70,
        'protein': 3,
        'carbs': 12,
        'fiber': 0,
        'fat': 1.5,
        'cholesterol': 15,
        'calcium': 0,
        'iron': .6,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 640,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0.0,
        'vitamin b6': 0.0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'tilapia': {
        'quantity': 1,
        'measure': 'fillet',
        'calories': 112,
        'protein': 23,
        'carbs': 0,
        'fiber': 0,
        'fat': 2.3,
        'cholesterol': 50,
        'calcium': 12,
        'iron': 0.6,
        'magnesium': 30,
        'potassium': 331,
        'sodium': 49,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0.08,
        'vitamin e': 0.79,
        'riboflavin': 0.073,
        'niacin': 0.0,
        'vitamin b6': 0.1,
        'folate': 24,
        'vitamin c': 0,
        'vitamin b12': 1.6,
        'selenium': 47,
        'sugar': 0,
        'vitamin d': 131
    },
    'string beans': {
        'quantity': .5,
        'measure': 'cup',
        'calories': 31,
        'protein': 1.8,
        'carbs': 7,
        'fiber': 3.4,
        'fat': .1,
        'cholesterol': 50,
        'calcium': 37,
        'iron': 1,
        'magnesium': 25,
        'potassium': 209,
        'sodium': 6,
        'zinc': 0.0,
        'vitamin a': 108,
        'thiamine': 0.1,
        'vitamin e': 0.41,
        'riboflavin': .65,
        'niacin': .125,
        'vitamin b6': 0.1,
        'folate': 333,
        'vitamin c': 16.3,
        'vitamin b12': 1.6,
        'selenium': .6,
        'sugar': 3.3,
        'vitamin d': 0
    },
    'yogurt': {
        'quantity': 1,
        'measure': 'cup',
        'weight': 170,
        'unit': 'g',
        'calories': 110,
        'protein': 11,
        'carbs': 6.1,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 8.5,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 61,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 3.3,
        'vitamin d': 0
    },
    'salad': {
        'quantity': 1,
        'measure': 'cup',
        'weight': 85,
        'unit': 'g',
        'calories': 24,
        'protein': 1,
        'carbs': 4,
        'fiber': 1,
        'fat': .4,
        'cholesterol': 0,
        'calcium': 20,
        'iron': 1,
        'magnesium': 0,
        'potassium': 295,
        'sodium': 39,
        'zinc': 0.0,
        'vitamin a': 315,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 60,
        'vitamin c': 9,
        'vitamin b12': 1.6,
        'selenium': .6,
        'sugar': 0,
        'vitamin d': 0
    },
    'cheese': {
        'quantity': .25,
        'measure': 'cup',
        'weight': 28,
        'unit': 'g',
        'calories': 110,
        'protein': 6,
        'carbs': 1,
        'fiber': 0,
        'fat': 8,
        'cholesterol': 25,
        'calcium': 197,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 170,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'tortilla': {
        'quantity': 1,
        'measure': 'item',
        'weight': 71,
        'unit': 'g',
        'calories': 210,
        'protein': 6,
        'carbs': 35,
        'fiber': 1,
        'fat': 4.5,
        'cholesterol': 0,
        'calcium': 130,
        'iron': 2.6,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 590,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'basmati': {
        'quantity': .25,
        'measure': 'cup',
        'weight': 45,
        'unit': 'g',
        'calories': 160,
        'protein': 4,
        'carbs': 35,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 0,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'sour cream': {
        'quantity': 2,
        'measure': 'tablespoons',
        'weight': 30,
        'unit': 'g',
        'calories': 60,
        'protein': 1,
        'carbs': 2,
        'fiber': 0,
        'fat': 5,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 15,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'ground beef': {
        'quantity': 3,
        'measure': 'oz',
        'weight': 85,
        'unit': 'g',
        'calories': 238,
        'protein': 24,
        'carbs': 0,
        'fiber': 0,
        'fat': 15,
        'cholesterol': 86,
        'calcium': 10,
        'iron': 2,
        'magnesium': 20,
        'potassium': 297,
        'sodium': 76,
        'zinc': 5.27,
        'vitamin a': 0,
        'thiamine': 0.05,
        'vitamin e': 0,
        'riboflavin': 0.20,
        'niacin': 5.07,
        'vitamin b6': 0.26,
        'folate': 9,
        'vitamin c': 0,
        'vitamin b12': 2,
        'selenium': 22,
        'sugar': 0,
        'vitamin d': 0
    }
}
